// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBls74CsYJWVrXomaZ6h9OYPsomJ1kaCjU',
    appId: '1:405193748477:web:0be2a9c6179ff949b5b394',
    messagingSenderId: '405193748477',
    projectId: 'akademikariyer-89f93',
    authDomain: 'akademikariyer-89f93.firebaseapp.com',
    storageBucket: 'akademikariyer-89f93.appspot.com',
    measurementId: 'G-0678W1F8GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6GhUYEedx8Y5CY2dGnm7_klled3RNpME',
    appId: '1:405193748477:android:f7fff49e4f081bf4b5b394',
    messagingSenderId: '405193748477',
    projectId: 'akademikariyer-89f93',
    storageBucket: 'akademikariyer-89f93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUurTjZt4Vgb3AbhL6UgYQqmd-OHTf3QM',
    appId: '1:405193748477:ios:4c7d8d06532f1734b5b394',
    messagingSenderId: '405193748477',
    projectId: 'akademikariyer-89f93',
    storageBucket: 'akademikariyer-89f93.appspot.com',
    iosClientId: '405193748477-u3jvfrk5d4eh6l09ma81saompimt4gqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.akademiKariyer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUurTjZt4Vgb3AbhL6UgYQqmd-OHTf3QM',
    appId: '1:405193748477:ios:4c7d8d06532f1734b5b394',
    messagingSenderId: '405193748477',
    projectId: 'akademikariyer-89f93',
    storageBucket: 'akademikariyer-89f93.appspot.com',
    iosClientId: '405193748477-u3jvfrk5d4eh6l09ma81saompimt4gqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.akademiKariyer',
  );
}
